### PR TITLE
[WIP][10.0] migration of product_variant_cost_price

### PR DESCRIPTION
**Pull request by dcorio**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please squash together all the "OCA Transbot..." commits (see https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests), and check Travis.

**Comment by pedrobaeza** [comment]
Please take into account #22 also

**Review by simahawk — APPROVED** [review]
quick code review: LGTM, except failing test and squash, of course :)

**Comment by pedrobaeza** [comment]
Travis is red. Is this going to be continued?

**Pull request closed without merging**
