### PR TITLE
11.0 mig product variant configurator

### PR DESCRIPTION
**Pull request by simoneversienti**

### CODE REVIEW

**Review by gurneyalex — CHANGES_REQUESTED** [review]
Travis is red

**Comment by GSLabIt** [comment]
any eta for this? thx

**Comment by pedrobaeza** [comment]
No answer from the contributor since a lot, so no.

**Comment by GSLabIt** [comment]
Thx, for the quick answer ..i'm not that odoo experienced ...but will try to have a look and fix travis error

**Comment by pedrobaeza** [comment]
No answer, so superseeding by #100

**Pull request closed without merging**
