### PR TITLE
[14.0][MIG] sale_order_line_variant_description

### PR DESCRIPTION
**Pull request by SimoneVagile**

### CODE REVIEW

**Comment by tafaRU** [comment]
@OCA/product-maintainers could you approve and run the pending workflow?

**Comment by tafaRU** [comment]
@SimoneVagile the order of the last three commits seems wrong:

image

Moreover, the second one should be squashed with that one of migration. In other words, you only should have two commits, in the following order:

-  `[IMP] sale_order_line_variant_description: black, isort, prettier`
-  `[14.0][MIG] sale_order_line_variant_description`

Could you please have a look?

**Comment by SimoneVagile** [comment]
> @SimoneVagile the order of the last three commits seems wrong:
> 
> image
> 
> Moreover, the second one should be squashed with that one of migration. In other words, you only should have two commits, in the following order:
> 
>     * `[IMP] sale_order_line_variant_description: black, isort, prettier`
> 
>     * `[14.0][MIG] sale_order_line_variant_description`
> 
> 
> Could you please have a look?

@tafaRU now seems to be ok

**Comment by tafaRU** [comment]
@rousseldenis could you please approve the following?

image

And also check why Travis build is not triggered. Thanks!

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by tafaRU** [comment]
@rousseldenis I see you just approved the PR, thanks! Do you know why Travis build is not triggered?

**Comment by rousseldenis** [comment]
> @rousseldenis I see you just approved the PR, thanks! Do you know why Travis build is not triggered?

No, wait a little.

**Review by tafaRU — COMMENTED** [review]
Code review: :+1: 
Approve once Travis build will be shown.

**Comment by SimoneVagile** [comment]
> Code review: +1
> Approve once Travis build will be shown.

@rousseldenis can you check this please?

**Comment by rousseldenis** [comment]
@OCA/core-maintainers Could you check Travis config for this repo? Thanks

**Comment by tafaRU** [comment]
@rousseldenis I think the reason for this behaviour is the following:

image

@SimoneVagile please try to do what is written on https://travis-ci.community/t/some-pr-are-not-analyzed-with-message-abuse-detected/1191/2

**Comment by rousseldenis** [comment]
> @rousseldenis I think the reason for this behaviour is the following:
> 
> image
> 
> @SimoneVagile please try to do what is written on https://travis-ci.community/t/some-pr-are-not-analyzed-with-message-abuse-detected/1191/2

So Travis 'AI' is detecting fraud build attempts? Wow

**Comment by rousseldenis** [comment]
So @SimoneVagile the idea is to log in on travis (with your gihub user).

**Comment by SimoneVagile** [comment]
@tafaRU @rousseldenis got it, thanks.

**Comment by tafaRU** [comment]
@SimoneVagile your PR is still flagged as potentially abusive. See https://travis-ci.com/github/OCA/product-variant/requests

**Comment by SimoneVagile** [comment]
> @SimoneVagile your PR is still flagged as potentially abusive. See https://travis-ci.com/github/OCA/product-variant/requests

I noticed that. I signed on [https://travis-ci.com](https://travis-ci.com) but I still can't trigger checks.

**Comment by sbidoul** [comment]
Hi folks, if you dare living on the bleeding edge, I can manually migrate the 14.0 branch of this repo to GitHub actions.

**Comment by sbidoul** [comment]
There you are: #1607

**Comment by tafaRU** [comment]
@SimoneVagile please squash together last two commits considering that changes to the README are related to tasks to do in the migration as written in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0#tasks-to-do-in-the-migration.

**Comment by SimoneVagile** [comment]
> @SimoneVagile please squash together last two commits considering that changes to the README are related to tasks to do in the migration as written in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0#tasks-to-do-in-the-migration.

Done, thanks.

**Comment by SimoneVagile** [comment]
@tafaRU @rousseldenis finally Travis build started :tada:

**Review by tafaRU — APPROVED** [review]

**Comment by SimoneVagile** [comment]
Can this be merged?

**Pull request merged**
