### PR TITLE
[14.0][MIG] product_variant_configurator

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Standard migration

CC @ForgeFlow

### CODE REVIEW

**Review by JasminSForgeFlow — APPROVED** [review]
LGTM!

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
@JordiBForgeFlow could you merge? the [v15 version](https://github.com/OCA/product-variant/pull/268) was already merged

**Review by etobella — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
@etobella please retry :)

**Pull request merged**
