### PR TITLE
[11.0][MIG] product_variant_supplierinfo: Migrate to 11.0

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This module is not needed anymore in v11, as it's a native feature.

**Comment by ghost** [comment]
@pedrobaeza apologies for inconvenience, but this is actually a migration of `product_variant_supplierinfo`, despite the former PR title :sweat_smile:

**Comment by pedrobaeza** [comment]
Yeah, but as said, it's a native feature. You have the field `product_id` now in core, and supplierinfo is handled at variant level.

**Comment by ghost** [comment]
point taken :slightly_smiling_face: 
the reason I'm saying this is that https://github.com/OCA/product-variant/issues/82 still lists `product_variant_supplierinfo`

**Comment by pedrobaeza** [comment]
That's because nobody has updated it with the information. I have done it now.

**Pull request closed without merging**
