### PR TITLE
[ADD] pv_sale_price: fix_price on variant_easy_edit view

### PR DESCRIPTION
**Pull request by robinkeunen**
Add `fix_price` to product_variant_easy_edit_view (the view from the template's "variants" button).

### CODE REVIEW

**Comment by robinkeunen** [comment]
I guess no one is interested in this ?

**Comment by robinkeunen** [comment]
very easy review though.

**Review by carmenbianca — APPROVED** [review]
LGTM

**Comment by carmenbianca** [comment]
Another review would be nice :)

**Pull request closed without merging**
