### PR TITLE
[15.0] [MIG] product_variant_configurator

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
Functional review. Works as expected.

**Comment by mariadforgeflow** [comment]
Hi @JasminSForgeFlow! I got the following error when creating a Product Variant:
image

I think that the issue arises because when clicking on the  Create button, product_tmpl_id has a value and it doesn't enter in the first return:
image

**Comment by JasminSForgeFlow** [comment]
> Hi @JasminSForgeFlow! I got the following error when creating a Product Variant: image
> 
> I think that the issue arises because when clicking on the Create button, product_tmpl_id has a value and it doesn't enter in the first return: image

It's fixed.
Thanks

**Review by mariadforgeflow — APPROVED** [review]
LGTM! Functional and code review.

**Review by DavidJForgeFlow — APPROVED** [review]
Works as expected, LGTM!

**Pull request merged**
