### PR TITLE
[FIX] 10.0 product_variant_default_code default reference_mask creation

### PR DESCRIPTION
**Pull request by PierrickBrun**
The condition for creating reference mask has a problem, it takes the code_prefix OR the attributes mask. This PR fixes it in order to create the reference mask with the code_prefix + the attributes mask.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why all these commits?

**Comment by PierrickBrun** [comment]
I reused an old branch, should I recreate a PR with a fresh fork ?

**Comment by pedrobaeza** [comment]
You can rebase your branch.

**Comment by PierrickBrun** [comment]
fixed here : https://github.com/OCA/product-variant/pull/90

**Pull request closed without merging**
