### PR TITLE
[FIX] product_variant_sale_price: avoid to update list price of all variants

### PR DESCRIPTION
**Pull request by tafaRU**
Steps to reproduce:
- create more than one variant
- change `fix_price` of one variant

Current behavior:
- `lst_price` of all variants are changed

Expected behavior:
- `lst_price` of only selected variant is changed

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@sergio-teruel please check

**Comment by tafaRU** [comment]
FYI, this bug was introduced by https://github.com/OCA/product-variant/pull/37/commits/4a7511fbb2ddfbb1e1df388cf0e926210097cae4 via https://github.com/OCA/product-variant/pull/37

**Comment by tafaRU** [comment]
@pedrobaeza, please set label as WIP.
My patch seeems do not work altough the bug is still there. :worried:

**Comment by pedrobaeza** [comment]
OK

**Comment by tafaRU** [comment]
I should have fixed :smiley: I confirm in a while.

**Comment by tafaRU** [comment]
@pedrobaeza, you could remove the label.
Thank you.

**Comment by pedrobaeza** [comment]
Done. Waiting for my colleague's opinion, who was the one that did the patch.

**Comment by anajuaristi** [comment]
The single thing it must be done, is to make invisible the lst_price on template when this module is installed.
I will recomend to go back to the original version of the module and avoid all the code you have 
 included because it was working perfectly just avoiding to change the price from template.

**Review by sergio-teruel — APPROVED** [review]

**Pull request merged**
