### PR TITLE
[16.0][ADD] product_variant_configurator: Migration to 16.0. Supersede migration

### PR DESCRIPTION
**Pull request by EvaSForgeFlow**
This is a continuation of: https://github.com/OCA/product-variant/pull/286

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
@hieulucky111 could you review? most of your comments in the original PR have been attended.

**Review by LoisRForgeFlow — APPROVED** [review]
Works as expected!

**Review by JordiBForgeFlow — APPROVED** [review]

**Pull request merged**
