### PR TITLE
[9.0] [ADD] sale_variant_configurator and sale_stock_variant_configurator

### PR DESCRIPTION
**Pull request by pedrobaeza**
Modules from odoomrp-wip that add the variant configurator in sales.

@Tecnativa

### CODE REVIEW

**Comment by DarioLodeiros** [comment]
I was testing the module and it seems to be functional, what is pending?

**Comment by pedrobaeza** [comment]
Reviews :wink:

**Comment by DarioLodeiros** [comment]
I think that the new product.product created from sale.order.line on confirm, does not take into account the extra price in attributes... ¿?, i think that it's a product_variant_configurator issue:  #68

**Comment by pedrobaeza** [comment]
But the problem should be in base module, not here. Please try on runbot and give all the steps on the opened issue.

**Comment by DarioLodeiros** [comment]
I cant run https://runbot.odoo-community.org/runbot/build/3275006
I tried a force rebuilt but after a while waiting, it gets put in skipped state... ¿?

**Comment by pedrobaeza** [comment]
I have rebased over current 9.0 branch, so it may work now.

**Comment by DarioLodeiros** [comment]
The module don't install
but the steps in my local docker are:
1.- activate attributes, config product with attribute x and extra price in x, and "dont create variants automatically".
2.- Create sale order with the product and attribute x... the unit price is the product price and it does not take into account the extra price in attributes
If you can fix the runbot, I go to try it

**Comment by pedrobaeza** [comment]
This has been retarget to v10, which is now completed, so I close.

**Pull request closed without merging**
