### PR TITLE
[10.0] product_variant_default_code: add code_prefix to the template's default_code

### PR DESCRIPTION
**Pull request by PierrickBrun**
From this issue : https://github.com/OCA/product-variant/issues/93

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@bealdav @sebastienbeau maybe you can check this one

**Comment by PierrickBrun** [comment]
I believe this addresses this issue https://github.com/OCA/product-variant/issues/96.

I did not change the 'Reference Prefix' name, maybe this would be something to do since it "replaces" the Reference now.

No need to make a change to the tree view since the default_code is populated with the code_prefix and is then shown in the appropriate field.

**Comment by sebastienbeau** [comment]
I have put this PR in work in progress, as we still miss the part of updating the prefix_code when we change the internal_reference of a simple product.

Moreover we should merge this PR before : https://github.com/OCA/product-variant/pull/94 as it solve many issue and rebase this branch on it.

I will review when it will be ready

**Comment by PierrickBrun** [comment]
Rebased from #94

**Comment by pedrobaeza** [comment]
Please rebase properly after merging the other PR.

**Comment by sebastienbeau** [comment]
@PierrickBrun I have fixed your rebased, you should fix the test (recursion)

**Review by bealdav — APPROVED** [review]

**Comment by PierrickBrun** [comment]
Hey, @chienandalu can you review this PR ? Many thanks

**Comment by pedrobaeza** [comment]
@chienandalu please take a look to this

**Review by chienandalu — APPROVED** [review]
Looks good to me. And cleaner as well :+1:

**Comment by bealdav** [comment]
ok mergeable PR, thanks

**Pull request merged**
