### PR TITLE
[13.0][MIG] product_variant_sale_price

### PR DESCRIPTION
**Pull request by Rad0van**
This is standard migration of product_variant_sale_price as a replacement of #177 that got stalled despite me providing suggestions on how to finish it. @Jerther please review.

### CODE REVIEW

**Review by Jerther — APPROVED** [review]

**Comment by tonygalmiche** [comment]
@rousseldenis why there is no access to runbot on this issue?

image

**Comment by rousseldenis** [comment]
No idea. Maybe @gurneyalex ?

**Review by HviorForgeFlow — APPROVED** [review]
Functional review

**Review by HaraldPanten — CHANGES_REQUESTED** [review]
IMO, public prices of the variants should be accessible and editable from:

Sales --> Products --> Product Variants. Then, selecting a variant and editing the price from the form view.

With the current performance, user can only change the prices this way, only if they do:

Sales --> Products. Select a product with variants, select variants smart button. Even though, Shouldn't there be only 1 field, where to change the product-product price, instead of 2? See this screenshot:

Captura de pantalla 2020-12-10 a las 18 51 53

User can change prices from the tree view, as allowed in V13:

Captura de pantalla 2020-12-10 a las 19 00 38


WDYT @HviorForgeFlow @Rad0van @rousseldenis ?

**Comment by Rad0van** [comment]
@HaraldPanten I just did straight migration. The reason why there are 2 fields is that it is actually added field (fix_price) that is used to trigger the recalculation. I can hide the original field if that is more desired.

I will check the other form (Sales --> Products --> Product Variants) and add the field there as well.

> IMO, public prices of the variants should be accessible and editable from:
> 
> Sales --> Products --> Product Variants. Then, selecting a variant and editing the price from the form view.
> 
> With the current performance, user can only change the prices this way, only if they do:
> 
> Sales --> Products. Select a product with variants, select variants smart button. Even though, Shouldn't there be only 1 field, where to change the product-product price, instead of 2? See this screenshot:
> 
> Captura de pantalla 2020-12-10 a las 18 51 53
> 
> User can change prices from the tree view, as allowed in V13:
> 
> Captura de pantalla 2020-12-10 a las 19 00 38
> 
> WDYT @HviorForgeFlow @Rad0van @rousseldenis ?

**Review by PierrickBrun — APPROVED** [review]
Functional review (in v14)

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Comment by HaraldPanten** [comment]
@rousseldenis @jgrandguillaume @emagdalenaC2i could you merge this one?

THX!

**Comment by HaraldPanten** [comment]
> /ocabot merge patch

THX!!

**Pull request merged**
