### PR TITLE
[16.0][mig]sale_order_line_variant_description: Migration to 16.0

### PR DESCRIPTION
**Pull request by dsolanki-initos**

### CODE REVIEW

**Comment by PicchiSeba** [comment]
LGTM

In order to please codecov, you should add tests for the lines highlighted [here](https://app.codecov.io/gh/OCA/product-variant/pull/296/blob/sale_order_line_variant_description/models/sale_order_line.py) in yellow
Or we could wait for a maintainer to manually approve this PR

**Review by PicchiSeba — APPROVED** [review]

**Review by HekkiMelody — APPROVED** [review]
Code and functional review, been using this PR for a few weeks now.

**Review by christian-ramos-tecnativa — APPROVED** [review]
LGTM

**Review by JordiMForgeFlow — APPROVED** [review]
LGTM 👍🏼

**Review by kluna1998 — APPROVED** [review]

**Comment by JordiMForgeFlow** [comment]
Hi @dsolanki-initos 

Could you rebase? Thank you :)

**Comment by JordiBForgeFlow** [comment]
Superseded by https://github.com/OCA/product-variant/pull/305, that has now been merged

**Pull request closed without merging**
