### PR TITLE
[17.0][MIG] product_variant_default_code: Migration to 17.0 

### PR DESCRIPTION
**Pull request by arantxa-s73**
Module migrated to version 17.0

### CODE REVIEW

**Comment by rousseldenis** [comment]
@arantxa-s73 Could you follow exactly the procedure described here:

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0#technical-method-to-migrate-a-module-from-160-to-170-branch

As some changes (like version number) should appear in migration commit. Thanks!

**Comment by rousseldenis** [comment]
Moreover, could you review #341 instead ?

**Comment by arantxa-s73** [comment]
I put the modifications in the migration pr

**Comment by arantxa-s73** [comment]
No change is necessary, to see the field it is necessary to be a member of a group.

**Pull request closed without merging**
