### PR TITLE
[14.0][ADD] product_matrix_show_color

### PR DESCRIPTION
**Pull request by miguel-S73**
This module shows colors of product variants in matrix table.
oca_product_matrix_show_color

### CODE REVIEW

**Comment by miguel-S73** [comment]
@pedrobaeza fixed

**Comment by miguel-S73** [comment]
@pedrobaeza , Can you  apply the "no stale" label?

**Review by pedrobaeza — APPROVED** [review]
Please find another reviewer and let's merge it instead.

**Review by ioans73 — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please rebase and see what is happening.

**Comment by miguel-S73** [comment]
@pedrobaeza rebase done and fixed red checks

**Pull request merged**
