### PR TITLE
Porting to Version 9.0 module product variant cost price

### PR DESCRIPTION
**Pull request by hurrinico**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
We should resolve https://github.com/OCA/product-variant/issues/22 in both v8 and v9

**Comment by eLBati** [comment]
It seems javieria@antiun.com is not associated to any github account

**Comment by pedrobaeza** [comment]
That mail is not valid anymore, but you can keep the name, because the attribution is correct. Please switch my name to "Tecnativa" in the credits, as this is my new company.

**Comment by hurrinico** [comment]
Useless PR in V9

**Pull request closed without merging**
