### PR TITLE
[15.0] [MIG] product_variant_configurator_manual_creation

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

### CODE REVIEW

**Review by JuanyDForgeflow — APPROVED** [review]
Functional review LGTM

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by etobella — APPROVED** [review]
No major changes

**Comment by etobella** [comment]
/ocabot migration product_variant_configurator_manual_creation

**Pull request merged**
