### PR TITLE
[ADD] mrp_variant_configurator: Migration to 11.0

### PR DESCRIPTION
**Pull request by SalahAdDin**
This is my first intent to add product configurator to the Manufacture module.

It still has a problem, i'm working to solve it.

TODO: 
- [ ] <del>Create products on change (form breaks when we edit the attributes' values).</del> General problem.
- [ ] <del>Proper description field (as **SO** description field).</del> General problem.

### CODE REVIEW

**Comment by SalahAdDin** [comment]
I found a first issue:

deepin-screen-recorder_select area_20181206122454
<del>While in **PO** it is not needed to create the product before at moment (don't check `create a product now!`), in **BoM** you must to do it before to save the _line_.
Why?</del>
It's a problem with configurator, we can find it in the default [module for purchases](https://github.com/OCA/product-variant/issues/120#issuecomment-444808756).

**Comment by pedrobaeza** [comment]
Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

**Comment by SalahAdDin** [comment]
I did all steps, and I squashed all commits to create just one commit with the new module.

**Comment by pedrobaeza** [comment]
But that's not the idea, as you are usurping the authorship of the rest. You can only squash commits from same author.

**Comment by SalahAdDin** [comment]
But, i'm the author to this module, i mean, it does not exist in previous versions afaik.

**Comment by pedrobaeza** [comment]
Ah, OK, then why do yo put `[MIG]` and try to add it in the migration issue? This is for migrations. In your case, it's an addition. Check https://www.odoo.com/documentation/11.0/reference/guidelines.html#tag-and-module-name for extra info.

**Comment by pedrobaeza** [comment]
Why do you close it? I don't get your way of acting most of the time...

**Comment by SalahAdDin** [comment]
I'm trying to change the tags to `ADD`.

Ok, i did: https://github.com/OCA/product-variant/pull/126

**Comment by pedrobaeza** [comment]
You don't need to create a new PR for that. Just edit GitHub PR title. And if you want to amend commit title, just do it locally, and forced push the branch.

**Comment by SalahAdDin** [comment]
Next time, i made a mistake: i deleted the branch and create a new one with the correct name. I'm sorry.

**Comment by pedrobaeza** [comment]
OK, no problem, just passing by the learning process as everybody.

**Pull request closed without merging**
