### PR TITLE
[MIG] 14.0 product_variant_sale_price

### PR DESCRIPTION
**Pull request by PierrickBrun**
no changes except version in manifest.

Based on https://github.com/OCA/product-variant/pull/188 , I will need to rebase if there are modifications.

### CODE REVIEW

**Review by dsolanki-initos — APPROVED** [review]
No Major change. 
Code Review and Functional Tests
LGTM

**Comment by dsolanki-initos** [comment]
It would be great if some can add review so that we can merge the PR.

**Review by bealdav — APPROVED** [review]

**Review by rvalyi — APPROVED** [review]

**Comment by dsolanki-initos** [comment]
@all can somone please merge this PR?

**Comment by dsolanki-initos** [comment]
@rvalyi It would be great if you can merge the PR

**Comment by dsolanki-initos** [comment]
It would be nice if we could merge the PR, Hence it is approved.

**Comment by dsolanki-initos** [comment]
It would be nice if we could merge the PR.
Thanks in Advance!

**Comment by dsolanki-initos** [comment]
It looks like the PR is ready to merge. Maintainer can you please merge it?

**Comment by dsolanki-initos** [comment]
It would be great if the maintainers can merge it.

**Comment by dsolanki-initos** [comment]
It would be great if the maintainers can merge it.

**Pull request merged**
