### PR TITLE
[17.0][MIG] product_variant_configurator: Migration to 17.0

### PR DESCRIPTION
**Pull request by manuelregidor**
Supersedes https://github.com/OCA/product-variant/pull/350

Standard migration

T-6149

### CODE REVIEW

**Comment by manuelregidor** [comment]
@HaraldPanten

**Review by Jaimermaccione — APPROVED** [review]
LGTM! Functional test on Runboat.
The functionality works well as tested on Runboat. 

Just a note that some terminology in the README does not exactly match what is seen in Runboat, but this inconsistency is also present in previous versions. I've attached a screenshot with the correct terms highlighted in red for reference. 
image

**Comment by manuelregidor** [comment]
@Jaimermaccione Done. Thank you.

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Pull request merged**
