### PR TITLE
[13.0][MIG] product_variant_default_code: Migration to 13.0

### PR DESCRIPTION
**Pull request by joao-p-marques**
TT26450

ping @chienandalu @pedrobaeza

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by tonygalmiche — APPROVED** [review]
LGTM : Functional review only with runbot

image

image

**Review by bodedra — CHANGES_REQUESTED** [review]
Functional review. :+1: 

Delete this file `product_variant_default_code/views/product_attribute_value_view.xml` because it introduce `Attribute Value Code` twice.

XML ID Ref: product.product_attribute_view_form

**Comment by joao-p-marques** [comment]
Thank you for the reviews.  
Changes made @bodedra

**Review by bodedra — APPROVED** [review]
Thanks @joao-p-marques LGTM :+1:

**Pull request merged**
