### PR TITLE
[13.0][FIX] product_variant_configurator: Fix creation of incorrect records when no name is provided

### PR DESCRIPTION
**Pull request by Rad0van**
This should be addressing issue #239

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Maybe it's better to not inject such context if the value is not in the dictionary?

**Comment by Rad0van** [comment]
> Maybe it's better to not inject such context if the value is not in the dictionary?

You mean something like
`obj = self.with_context(product_name=vals.get("name")) if "name" in vals else self`
I'm sure there's more elegant way to write this in Python but would it still be more elegant than the proposed version? I mean I can see the check in product.template is `if "product_name" in self.env.context` so it would be nice if actually that was how the condition was constructed (presence or lack there of it in context). Please suggest how to write it in a nice Python-ic way...

**Comment by pedrobaeza** [comment]
Your suggestion is elegant enough.

**Comment by Rad0van** [comment]
> Your suggestion is elegant enough.

Not to me :-) How about do the magic with swapping name inside product.template create method and completely remove the context voodoo? So in product.template create method there would be something like this:
```
@api.model 
def create(self, vals): 
     vals["name"] = vals.get("product_name", False)
     return super(ProductTemplate, self).create(vals) 
```
The line in product.product create method would just set that value instead of injecting it into context.

Just an idea. Please comment.

**Comment by pedrobaeza** [comment]
If you do that, please add docstring explaining why it's done, so this is not removed in the future if the usefulness is not seen.

**Comment by Rad0van** [comment]
> If you do that, please add docstring explaining why it's done, so this is not removed in the future if the usefulness is not seen.

OK. But which would you prefer? What would you consider better?

**Comment by pedrobaeza** [comment]
The last one seems OK.

**Comment by Rad0van** [comment]
> The last one seems OK.

Somehow that didn't work. So I stuck with the former. Seems OK. I'll squash the commits together.

**Comment by pedrobaeza** [comment]
Maybe you can create a test case for reproducing the problem and thus avoid regressions and see the better fix.

**Comment by Rad0van** [comment]
> Maybe you can create a test case for reproducing the problem and thus avoid regressions and see the better fix.

What I meant it didn't work was that with that alternative approach the tests failed even with correct inputs. For me this is good enough even though I didn't get that Python elegance I was hoping for. So if it's good enough for you I have lots of importing updated price lists (that with the bug were creating unnamed product templates and variants previously instead of failing).

**Review by pedrobaeza — APPROVED** [review]
Please squash

**Comment by Rad0van** [comment]
> Please squash

It was done at the time. Is the commit message OK or that needs to be more informative as well?

**Comment by pedrobaeza** [comment]
I'm afraid not. Please follow commit message guidelines: https://www.odoo.com/documentation/15.0/es/developer/misc/other/guidelines.html#commit-message-structure

**Comment by Rad0van** [comment]
> I'm afraid not. Please follow commit message guidelines: https://www.odoo.com/documentation/15.0/es/developer/misc/other/guidelines.html#commit-message-structure

Done. Thanx for the pointer.

**Review by pedrobaeza — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]
This should be covered by a test to avoid regression

**Comment by MiquelRForgeFlow** [comment]
@Rad0van Shouldn't this PR be forward ported?

**Comment by Rad0van** [comment]
> @Rad0van Shouldn't this PR be forward ported?

Not sure but probably yes.

**Pull request merged**
