### PR TITLE
[10.0][MIG] sale_order_line_variant_description module

### PR DESCRIPTION
**Pull request by tafaRU**

### CODE REVIEW

**Comment by hurrinico** [comment]
IMHO 👍

**Review by eLBati — APPROVED** [review]
thanks

**Review by rami-wafaie — APPROVED** [review]
:+1:

**Comment by rami-wafaie** [comment]
@pedrobaeza can you please have a look at it ?

**Comment by tafaRU** [comment]
Thanks @rami-wafaie for the approve!
I'm glad to see that the training has been helpful :wink:

**Pull request merged**
