### PR TITLE
[17.0][MIG] product_variant_configurator: Migration to 17.0

### PR DESCRIPTION
**Pull request by BT-dmoreno**

### CODE REVIEW

**Comment by HaraldPanten** [comment]
Hi @BT-dmoreno Will you continue with this PR?

THX

**Comment by pedrobaeza** [comment]
To include #357

**Comment by BT-dmoreno** [comment]
@HaraldPanten yes, I think I'm close to finish it. Tomorrow probably will have some time and hopefully I'm done. I need to squash my commits and make sure all tests are passed.

**Comment by HaraldPanten** [comment]
> @HaraldPanten yes, I think I'm close to finish it. Tomorrow probably will have some time and hopefully I'm done. I need to squash my commits and make sure all tests are passed.

Nice! 👍

**Comment by HaraldPanten** [comment]
Superseded by https://github.com/OCA/product-variant/pull/358

**Pull request closed without merging**
