### PR TITLE
[WIP][10.0] migration of product_variant_sale_price

### PR DESCRIPTION
**Pull request by dcorio**
based on:
https://github.com/OCA/product-variant/pull/26

### CODE REVIEW

**Comment by pedrobaeza** [comment]
The same about "OCA Transbot" commits and Travis.

**Review by simahawk — CHANGES_REQUESTED** [review]
quick code review: LGTM, except failing test and squash, of course :)

**Comment by tafaRU** [comment]
@dcorio, if you agree, I'd continue on https://github.com/tafaRU/product-variant/tree/10.0-mig-product_variant_sale_price.

**Comment by dcorio** [comment]
@tafaRU sure, thanks. no time on my side to work on this right now.

**Comment by pedrobaeza** [comment]
Travis is red. Is this going to be continued?

**Pull request closed without merging**
