### PR TITLE
[14.0] [MIG] product_variant_configurator_manual_creation

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

Depends on:
- https://github.com/OCA/product-variant/pull/264

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@JasminSForgeFlow it seems migration commit was squashed by error

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by HviorForgeFlow — APPROVED** [review]
Code review :+1:

**Comment by HviorForgeFlow** [comment]
@OCA/product-maintainers could you reopen the PR and move it forward? Thanks!

**Pull request merged**
