### PR TITLE
[12.0][MIG] purchase_order_variant_mgmt

### PR DESCRIPTION
**Pull request by grindtildeath**
Based on https://github.com/OCA/product-variant/pull/109

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please squash together all migration commits from the other contributor.

**Comment by grindtildeath** [comment]
@pedrobaeza I didn't intend to replace #109, as this is for v12.0

**Comment by pedrobaeza** [comment]
OK, I see... I have been very quick. Any way, you should squash that commits.

**Review by TDu — APPROVED** [review]

**Review by sebalix — APPROVED** [review]

**Pull request merged**
