### PR TITLE
[15.0] [MIG] sale_order_line_variant_description

### PR DESCRIPTION
**Pull request by OSevangelist**

### CODE REVIEW

**Review by christian-ramos-tecnativa — APPROVED** [review]
LGTM

**Comment by OSevangelist** [comment]
It seems that class 'wrapt' cannot be imported using Python 3.11 and that causes the mandatory pre-commit tests to fail on this PR. The issue is explained for instance here https://github.com/GrahamDumpleton/wrapt/issues/196 

Maybe someone has an idea how to fix that, @sbidoul ? I am happy to do it myself but i have no clue where to get that fixed in our tool chain to be consistent across repositories. Thanks for the help @azoellner to identify the issue

**Comment by sbidoul** [comment]
Try `pipx run copier -f update`. There is a fair chance this is already fixed in the latest project template.

**Comment by OSevangelist** [comment]
@sbidoul that seems to have worked. thanks for the help and sorry for the time it took me to apply them. I an gonna merge this trivial change now

**Pull request merged**
