### PR TITLE
[17.0][mig] product variant sale price: Migration to 17.0

### PR DESCRIPTION
**Pull request by pedroguirao**

### CODE REVIEW

**Review by ioans73 — APPROVED** [review]
Functional review 👍🏻

**Review by antoniocanovas — APPROVED** [review]
Functional review OK !!

**Review by Jaimermaccione — APPROVED** [review]
LGTM! Functional review on runboot

**Review by HaraldPanten — APPROVED** [review]
Seems to be working fine 👍

**Pull request merged**
