### PR TITLE
[13.0][NEW]product_variant_configurator_website_sale

### PR DESCRIPTION
**Pull request by Rad0van**
This is an attempt to create required glue module as described in #192 @pedrobaeza and @HviorForgeFlow could you please have a look? Thank you.

### CODE REVIEW

**Comment by Rad0van** [comment]
This is pretty minimal/trivial. @pedrobaeza and @HviorForgeFlow would you care to have a look? Thanx.

**Comment by Rad0van** [comment]
@rousseldenis /  @pedrobaeza / @HviorForgeFlow would you care to have a look? Thanx.

**Review by pedrobaeza — APPROVED** [review]

**Review by HviorForgeFlow — APPROVED** [review]

**Comment by Rad0van** [comment]
@pedrobaeza @dreispt fixed. Please start merge again. Thanx.

**Pull request merged**
