### PR TITLE
[FIX] inherited form does not have Lots

### PR DESCRIPTION
**Pull request by kingofsevens**
When running gives XML error.. this fixes and places the page item..

### CODE REVIEW

**Comment by rvalyi** [comment]
:-1:   reject

Hello @kingofsevens 

If I'm not wrong, the variant modules will need some ground rework in v8/master after OpenERP SA improved the variant management in the core but without considering very well OCA developments unfortunately.

I need to talk in more details with the latest projects maintainers such as @sebastienbeau but I think we will just move the module to an 'unported' folder on master or v8 to explicit the module were not ported yet and then later we would rework them for V8/master.

Therefore I current reject your merge proposal, I hope you understand. If you want to contribute, then the steps are the ones I mentioned I believe.

What do you think.

**Comment by kingofsevens** [comment]
Well, no offense taken. We have recently used these modules in a project. I wanted to do a quick fix. This is essential if someone wants to use this in v7, but I totally agree to a move to 'unported' folder since most of the work is done by v8 in the core.

**Comment by rvalyi** [comment]
wait a minute, your fix is for v7?

If so please do the merge proposal against the 7.0 branch (you proposed it against "master"). Could you confirm?

**Comment by kingofsevens** [comment]
Oops my bad. Yes it is against 7.0 branch.. I shall create another pull request then..

**Comment by rvalyi** [comment]
that's why then. Thanks.

**Pull request closed without merging**
