### PR TITLE
[8.0] [ADD] purchase_product_variant_configurator

### PR DESCRIPTION
**Pull request by lmignon**
This one depends of #38

This PR follows the discussion on the #38 and:
- add `purchase_product_variants` from from https://github.com/odoomrp/odoomrp-wip/tree/8.0/purchase_product_variants
- adapt/improve `purchase_product_variants` for OCA (Thanks to @zakiuu)

### CODE REVIEW

**Comment by lmignon** [comment]
@zakiuu I've split your initial work on https://github.com/acsone/product-variant/tree/8.0-add_product_variant_configurator_original into 2 separate PRS as proposed by @pedrobaeza.
In the same time I have extracted correctly the commit history and merge your work  for `purchase_product_variants`. in https://github.com/OCA/product-variant/pull/43/commits/1d93b37d352de63099334f53a3a6f144c17fa4b9

**Comment by zakiuu** [comment]
@lmignon Thanks, Next time show me how I do it so I can learn :)

**Comment by pedrobaeza** [comment]
We talked about renaming this module to _purchase_product_variant_configurator_, to follow same scheme and OCA rules. Can you please perform the renaming?

**Comment by lmignon** [comment]
@pedrobaeza the work on these modules (#38 #43) by @zakiuu will continue on 9.0. Indeed, we need these modules on 9.0.

**Comment by pedrobaeza** [comment]
OK, no problem. Do you think this one is ready to be merged as is?

**Comment by sbidoul** [comment]
I'm closing this. If there is interest for 8.0 a backport from the 9.0 branch is the way to go.

**Pull request closed without merging**
