### PR TITLE
[13.0][MIG] purchase_variant_configurator

### PR DESCRIPTION
**Pull request by ThomasBinsfeld**
refs #155

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
Hi @ThomasBinsfeld are still on this? Maybe a with just a rebase you would pass the CI

**Comment by ThomasBinsfeld** [comment]
> Hi @ThomasBinsfeld are still on this? Maybe a with just a rebase you would pass the CI

Done

**Comment by rousseldenis** [comment]
runbot error due to https://github.com/odoo/odoo/pull/63884

**Comment by chienandalu** [comment]
Indeed my proposition in the migration of `sale_variant_configurator` is to get rid of that field in the mixin, wich seems to be unnecessary solves the problem: https://github.com/OCA/product-variant/pull/204/files#diff-da880cc7befc12d224f5853cd6b452dbbc02c1074d03c2019391c7630f1bb4aeL37

**Comment by pedrobaeza** [comment]
The module `sale_variant_configurator` has been merged with the patch to remove the runbot warning. @chienandalu is this PR OK for you to continue merging?

**Review by pedrobaeza — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
