### PR TITLE
[FIX] website URI

### PR DESCRIPTION
**Pull request by sbidoul**

### CODE REVIEW

**Review by simahawk — APPROVED** [review]

**Comment by simahawk** [comment]
BTW: most of the modules have companies' website instead of OCA. A script could fix them all :)

**Comment by bealdav** [comment]
Thanks @sbidoul 

If you modify website key, could you remove space line 12 (author key)

Thank you

**Review by bealdav — APPROVED** [review]

**Comment by sbidoul** [comment]
@simahawk I'm happy to write a script to apply the change globally. Waiting for https://github.com/OCA/maintainer-tools/pull/276 to be merged.

**Comment by simahawk** [comment]
@sbidoul ah, sorry, I thought it was already merged :stuck_out_tongue:

**Comment by sbidoul** [comment]
@simahawk at this stage, I'm just manually fixing those which break the pypi upload.

**Review by MiquelRForgeFlow — APPROVED** [review]

**Pull request merged**
