### PR TITLE
[MIG] purchase_variant_configurator: Migration to 10.0

### PR DESCRIPTION
**Pull request by chienandalu**
Purchase - Product variants
===========================

This module allows you to create the product variant when a purchase order is
confirmed. It adds to the purchase line a product configurator, so that
selecting a product and its attributes can be created a new product variant.

Depends on:

- [x] product_variant_configurator: https://github.com/OCA/product-variant/pull/65

cc @Tecnativa

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Tentatively :+1: while the dependency is not merged

**Comment by pedrobaeza** [comment]
Please rebase now that the dependency is merged.

@luismontalba please review

**Comment by chienandalu** [comment]
@luismontalba There you have it :)

**Comment by luismontalba** [comment]
Testing on runbot I get an error when I follow this steps:

paso1

paso2

paso3

**Comment by pedrobaeza** [comment]
Is something related to the PR?

**Comment by luismontalba** [comment]
No, I think it's not related.

**Review by luismontalba — APPROVED** [review]
Tested on runbot

**Pull request merged**
