### PR TITLE
[13.0] product_variant_default_code improvements

### PR DESCRIPTION
**Pull request by Rad0van**
After playing with this module (which I found very useful) I felt the need to do few improvements:

- allow for editing of product.attribute code
- enhance the documentation here and there to show where that code might be used
- enhance the documentation with System Settings and code_prefix usage

### CODE REVIEW

**Comment by Rad0van** [comment]
@pedrobaeza , @ernestotejeda , @pedrocasi would you care to have a look? Thank you.

**Review by ernestotejeda — APPROVED** [review]
LGTM

**Comment by Rad0van** [comment]
@pedrobaeza , @chienandalu, @pedrocasi sorry to bother - would any of you have a look? This is pretty trivial and improves documentation a bit.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
