### PR TITLE
[MIG] product_variant_default_code: migration to 16.0

### PR DESCRIPTION
**Pull request by Rferri44-S73**
Standard migration to 16.0

Depends https://github.com/OCA/product-attribute/pull/1301

### CODE REVIEW

**Comment by Rferri44-S73** [comment]
@pedrobaeza This PR could be merged?

**Comment by pedrobaeza** [comment]
Please remove last 2 commits

**Comment by Rferri44-S73** [comment]
@pedrobaeza it's done

**Comment by pedrobaeza** [comment]
Hey, I'm seeing this has introduced a wild dependency that is not appropriate and using something not merged (#274), which is [20320aa](https://github.com/OCA/product-variant/pull/287/commits/20320aa0abc6ad7ef347d5e2a4b52010e45c4513)

I'm reverting now such part.

**Pull request merged**
