### PR TITLE
[13.0][FIX] product_variant_configurator: _build_attributes_domain

### PR DESCRIPTION
**Pull request by jo541**
Fully manage dictionaries in _build_attributes_domain.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you please specify a bit more?

**Comment by jo541** [comment]
At the base the method managed only partially the possibility to spend product_attributes like a dictionary.

Line 40: An if condition check the possibility of the  product_attributes contain dictionaries or records. 
Line 51: Another loop on product_attributes is managed only like records.

**Comment by pedrobaeza** [comment]
When a dict is passed in the current code? Is that something custom on your side?

**Comment by jo541** [comment]
It's in the current code.

Current code :
The method _build_attributes_domain have a param product_attributes, this param is iterated at the line 39. In this loop at the line 40 a check verify if param contain a list of dict or records. This check lets think that param could be a list of dict. 

But at the line 51 a list comprehension iterate on product_attributes. This list comprehension only work in the case of the param product_attributes are records. Not if the product_attributes is a list of dict.

In the MR:

Move the list comprehension at the line 51 to a new loop for at the line 39 to manage the case of the param is a list of dict or records

**Review by pedrobaeza — APPROVED** [review]
Not sure if that's dead code on current module, but better to be coherent.

**Review by ThomasBinsfeld — APPROVED** [review]

**Pull request merged**
