### PR TITLE
[FIX] product_variant_sale_price: writting template list_price should not write its variants

### PR DESCRIPTION
**Pull request by oihane**
related to bug introduced by 4a7511f via #37

Related to: https://github.com/OCA/product-variant/pull/80#issuecomment-338980134

cc @pedrobaeza @sergio-teruel @tafaRU @anajuaristi

### CODE REVIEW

**Comment by tafaRU** [comment]
Please see https://github.com/OCA/product-variant/commit/4a7511fbb2ddfbb1e1df388cf0e926210097cae4#commitcomment-25207887

**Comment by anajuaristi** [comment]
We need this module to be working so please, we need @oihane 's PR to be merged asap

**Review by Daniel-CA — APPROVED** [review]

**Comment by anajuaristi** [comment]
@gurneyalex please, could you merge this one. I have no permissions on this repository

**Comment by Daniel-CA** [comment]
PR #80 should be checked, @tafaRU fixed there.

**Comment by pedrobaeza** [comment]
Closing as #80 is merged.

**Pull request closed without merging**
